// SPDX-License-Identifier: MIT
pragma solidity =0.8.27;

import {StakeInfo} from "../libraries/LibHyperStaking.sol";

/**
 * @title IAllocation
 * @dev Interface for AllocationFacet
 */
interface IAllocation {
    //============================================================================================//
    //                                          Events                                            //
    //============================================================================================//

    event Join(
        address indexed strategy,
        address indexed user,
        uint256 stake,
        uint256 allocation
    );

    event Leave(
        address indexed strategy,
        address indexed user,
        uint256 stake, // amount requested
        uint256 allocation
    );

    event StakeCompounded(
        address indexed strategy,
        address indexed feeRecipient,
        uint256 feeRate,
        uint256 feeAmount,
        uint256 feeAllocation,
        uint256 stakeAdded
    );

    event BridgeSafetyMarginUpdated(
        address indexed strategy,
        uint256 oldMargin,
        uint256 newMargin
    );

    event FeeRecipientUpdated(
        address indexed strategy,
        address indexed oldRecipient,
        address indexed newRecipient
    );

    event FeeRateUpdated(
        address indexed strategy,
        uint256 oldRate,
        uint256 newRate
    );

    //============================================================================================//
    //                                          Errors                                            //
    //============================================================================================//

    error AsyncAllocationNotSupported();

    error StrategyDoesNotExist(address strategy);

    error FeeRecipientUnset();
    error ZeroFeeRecipient();
    error FeeRateTooHigh();

    error InsufficientRevenue();
    error SafetyMarginTooHigh();

    error ZeroStakeExit();
    error ZeroAllocationExit();


    //============================================================================================//
    //                                          Mutable                                           //
    //============================================================================================//

    /**
     * @notice Join for a specified strategy by staking a certain amount
     * @param strategy The strategy for which the user is joining
     * @param user The address of the user
     * @param stake The stake amount
     */
    function join(address strategy, address user, uint256 stake) external payable;

    /**
     * @notice Leave for a specified strategy and asset amount
     * @param strategy The strategy from which the user is leaving
     * @param user The address of the user
     * @param allocation The amount of asset allocation in strategy
     * @return The total withdrawal amount, including the stake, generated revenue, after fees
     */
    function leave(
        address strategy,
        address user,
        uint256 allocation
    ) external returns (uint256);

    /**
     * @notice Harvests revenue for a specific strategy and compound it
     * @dev The possible amount to report is adjusted by bridgeSafetyMargin
     */
    function report(address strategy) external;

    /**
     * @notice Sets the bridge safety margin (with 18 dec precision) for a specific strategy
     * @dev The safety margin cannot be set below the minimum allowed value (2% - 2e16)
     */
    function setBridgeSafetyMargin(address strategy, uint256 newMargin) external;

    /**
     * @notice Updates the fee recipient for a given strategy
     * @param strategy The strategy whose fee recipient is being set
     * @param newRecipient The new recipient address
     */
    function setFeeRecipient(address strategy, address newRecipient) external;

    /**
     * @notice Updates the fee rate for a given strategy
     * @dev The new rate must be `<= 1e18` (i.e. 100%).
     * @param strategy The vault/strategy whose rate is being set.
     * @param newRate The new fee rate (1e18 == 100%).
     */
    function setFeeRate(address strategy, uint256 newRate) external;

    //============================================================================================//
    //                                           View                                             //
    //============================================================================================//

    /**
     * @notice Retrieves information for a specified strategy
     * @param strategy The address of the strategy
     * @return The StakeInfo struct containing information about this specific strategy
     */
    function stakeInfo(address strategy) external view returns (StakeInfo memory);

    /*
     * @notice Returns the revenue generated by a specific strategy
     * @dev This function calculates and returns the revenue for the given strategy
     * @param strategy The address of the strategy to check
     * @return The revenue amount (in stake currency)
     */
    function checkRevenue(address strategy) external view returns (uint256);
}
