// SPDX-License-Identifier: UNLICENSED
pragma solidity =0.8.27;

import {StakeInfo} from "../libraries/LibHyperStaking.sol";

/**
 * @title IStakeVault
 * @dev Interface for StakeVaultFacet
 */
interface IStakeVault {
    //============================================================================================//
    //                                          Events                                            //
    //============================================================================================//

    event Join(
        address indexed strategy,
        address indexed user,
        uint256 allocation
    );

    event Leave(
        address indexed strategy,
        address indexed user,
        uint256 stake,
        uint256 allocation
    );

    event RevenueCollected(
        address indexed strategy,
        address indexed to,
        uint256 revenueAmount
    );

    event BridgeSafetyMarginUpdated(
        uint256 oldMargin,
        uint256 newMargin
    );

    //============================================================================================//
    //                                          Errors                                            //
    //============================================================================================//

    error InsufficientRevenue();
    error SafetyMarginTooLow();

    //============================================================================================//
    //                                          Mutable                                           //
    //============================================================================================//

    /**
     * @notice Join for a specified strategy by staking a certain amount
     * @param strategy The strategy for which the user is joining
     * @param user The address of the user
     * @param stake The stake amount
     */
    function join(address strategy, address user, uint256 stake) external payable;

    /**
     * @notice Leave for a specified strategy and asset amount
     * @param strategy The strategy from which the user is leaving
     * @param user The address of the user
     * @param allocation The amount of asset allocation from ValutToken
     * @return The total withdrawal amount, including the stake, generated revenue, after fees
     */
    function leave(
        address strategy,
        address user,
        uint256 allocation
    ) external returns (uint256);

    /**
     * @notice Collects revenue for a specific strategy and sends it to the target address
     * @dev The possible amount to collect is already adjusted by bridgeSafetyMargin
     */
    function collectRevenue(address strategy, address to, uint256 amount) external;

    /**
     * @notice Sets the bridge safety margin (with 18 dec precision) for a specific strategy
     * @dev The safety margin cannot be set below the minimum allowed value (2% - 2e16)
     */
    function setBridgeSafetyMargin(address strategy, uint256 newMargin) external;

    //============================================================================================//
    //                                           View                                             //
    //============================================================================================//

    /**
     * @notice Retrieves information for a specified strategy
     * @param strategy The address of the strategy
     * @return The StakeInfo struct containing information about this specific active strategy
     */
    function stakeInfo(address strategy) external view returns (StakeInfo memory);

    /*
     * @notice Returns the revenue generated by a specific strategy
     * @dev This function calculates and returns the revenue for the given strategy
     * @param strategy The address of the strategy to check
     * @return The revenue amount (in stake currency)
     */
    function checkRevenue(address strategy) external view returns (uint256);
}
