// SPDX-License-Identifier: UNLICENSED
pragma solidity =0.8.27;

/**
 * @title IStaking
 * @dev Interface for StakingFacet
 */
interface IStaking {
    //============================================================================================//
    //                                          Events                                            //
    //============================================================================================//

    event StakeDeposit(
        address from,
        address indexed to,
        address indexed strategy,
        uint256 stake,
        uint8 indexed tier  // 1 - Tier1
                            // 2 - Tier2
    );

    event StakeWithdraw(
        address from,
        address indexed to,
        address indexed strategy,
        uint256 stake,
        uint256 withdrawAmount
    );

    //============================================================================================//
    //                                          Errors                                            //
    //============================================================================================//

    /// @notice Thrown when attempting to deposit to a non-existent vault
    error VaultDoesNotExist(address vault);

    //============================================================================================//
    //                                          Mutable                                           //
    //============================================================================================//

    /**
     * @notice Deposits a specified stake amount into the chosen strategy
     * @param strategy The address of the strategy selected by the user
     * @param stake The amount of the token to stake
     * @param to The address receiving the staked token allocation (typically the user's address)
     */
    function stakeDeposit(
        address strategy,
        uint256 stake,
        address to
    ) external payable;

    /**
     * @notice Deposits a specified stake amount into the chosen strategy
     * @param strategy The address of the strategy selected by the user
     * @param stake The amount of the token to stake
     * @param to The address receiving the staked token allocation (typically the user's address)
     */
    function stakeDepositTier2(
        address strategy,
        uint256 stake,
        address to
    ) external payable;

    /**
     * @notice Withdraws a specified stake amount, including revenue generated by the strategy
     * @param strategy The address of the strategy used during staking
     * @param stake The amount of the staked token to withdraw
     * @param to The address to receive the withdrawn tokens
     * @return withdrawAmount The total amount withdrawn, including the initial stake
     *         and any generated revenue
     * @dev withdrawAmount = initial stake amount + revenue generated by the strategy
     */
    function stakeWithdraw(
        address strategy,
        uint256 stake,
        address to
    ) external returns (uint256 withdrawAmount);

    /**
     * @notice Pauses stake functionalities
     */
    function pauseStaking() external;

    /**
     * @notice Resumes stake functionalities
     */
    function unpauseStaking() external;
}
